# Generated by Django 4.0.6 on 2022-07-22 05:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUserAuth',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=2000, null=True)),
                ('emp_position', models.CharField(max_length=50)),
                ('emp_salary', models.CharField(max_length=50)),
                ('emp_experience', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('age', models.IntegerField(max_length=10)),
                ('DOB', models.IntegerField(max_length=10)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empapp.employeeuserauth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('companyname', models.CharField(blank=True, max_length=250, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=5)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empapp.employeeuserauth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
