# Generated by Django 4.0.6 on 2022-07-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_alter_employeeuserauth_managers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeeuserauth',
            table='empapp_employeeuserauth',
        ),
    ]
