# Generated by Django 4.0.6 on 2022-07-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0005_alter_employeeuserauth_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeeuserauth',
            table='employeeuserauth',
        ),
    ]
