# Generated by Django 4.0.6 on 2022-07-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0007_employeeuserauth_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeeuserauth',
            table=None,
        ),
    ]
